name: Publishes to GitHub
description: Publishes updates on a new Maven Central release to GitHub

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Determine previous tag"
      shell: bash
      # list tags in reverse order and extract the 2nd line to learn the
      # previous tag
      run: |
        tagl=$(git tag -l | sed "s/'/\\\'/g" | sed 's/"/\\"/g')
        echo -e "tag -l: $tagl"

    - name: "Determine previous tag"
      shell: bash
      run: |
        tags=$(git tag)
        echo -e "tags:\n$tags"
        sorted_by_version=$(sort -V <<< "$tags")
        echo -e "sorted_by_version: $sorted_by_version"
        grepped=$(grep -B 1 `git describe --tags` <<< "$sorted")
        echo -e "grepped: $grepped"
        prevTag=$(head -1 <<< "$grepped")
        echo -e "prevTag: $prevTag"
        
        prev_tag=$(sed -n '2p' <<< "$tags")
        echo -e "prev_tag: $prev_tag"
        echo "PREV_TAG=$prev_tag" >> "GITHUB_ENV"

    - name: "Determine previous tag 1"
      shell: bash
      # list tags in reverse order and extract the 2nd line to learn the
      # previous tag
      run: |
        {
          echo "PREV_TAG_1<<EOF"
          `/bin/bash -c "git tag --sort=-v:refname | sed -n '2p'"`
          echo EOF
        } >> "$GITHUB_ENV"

    - name: "Determine previous tag 2"
      shell: bash
      # list tags in reverse order and extract the 2nd line to learn the
      # previous tag
      run: |
        pev_tag=`/bin/bash -c "git tag --sort=-v:refname | sed -n '2p'"`
        echo "prev_tag: $prev_tag"
        echo "PREV_TAG_2=$prev_tag" >> "$GITHUB_ENV"

    - name: "Determine previous tag 3"
      shell: bash
      # list tags in reverse order and extract the 2nd line to learn the
      # previous tag
      run: |
        {
          echo "PREV_TAG_3<<EOF"
          $(/bin/bash -c "git tag --sort=-v:refname | sed -n '2p'")
          echo EOF
        } >> "$GITHUB_ENV"

    - name: "Print previous tag"
      shell: bash
      run: |
        echo "prev tag: ${{ env.PREV_TAG }}"
        echo "cur tag: ${{ github.ref_name }}"

    - name: "Generate changelog"
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ inputs.github-token }}
        head-ref: ${{ github.ref_name }}
        base-ref: ${{ env.PREV_TAG }}

    - name: "Publish to GitHub Repository"
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Grab the new version from Maven Central https://repo1.manven.org/maven2/net/kessra/test-release-pipeline/${{ github.ref_name }}/ by using it in your deps
          
          ```
          <dependencies>
            <dependency>
                <groupId>net.kessra</groupId>
                <artifactId>test-release-pipeline</artifactId>
                <version>${{ github.ref_name }}</version>
            </dependency>
          </dependencies>
          ```
          
          ### Things that changed in this release
          ${{ steps.changelog.outputs.changelog }}
        token: ${{ inputs.github-token }}