name: Publishes to GitHub
description: Publishes updates on a new Maven Central release to GitHub

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ inputs.github-token }}
    - name: Publish to GitHub Repository
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body: |
          Grab the new version from Maven Central https://repo1.manven.org/maven2/net/kessra/test-release-pipeline/${{ github.ref }}/ by using it in your deps
          
          ```
          <dependencies>
            <dependency>
                <groupId>net.kessra</groupId>
                <artifactId>test-release-pipeline</artifactId>
                <version>${{ github.ref }}</version>
            </dependency>
          </dependencies>
          ```
          
          ### Things that changed in this release
          ${{ steps.changelog.outputs.changelog }}
        token: ${{ inputs.github-token }}