name: Publishes to GitHub
description: Publishes updates on a new Maven Central release to GitHub

inputs:
  github-token:
    description: 'Github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: "Determine previous tag"
      shell: bash
      run: |
        git fetch --all --tags
        prev_tag=$(git tag | sort -V | grep -B 1 ${{ github.ref_name }} | head -1)
        echo -e "prev_tag: $prev_tag"
        echo "PREV_TAG=$prev_tag" >> "GITHUB_ENV"

    - name: "Print previous tag"
      shell: bash
      run: |
        echo "prev tag: ${{ env.PREV_TAG }}"
        echo "cur tag: ${{ github.ref_name }}"

    - name: "Generate changelog"
      id: changelog
      uses: metcalfc/changelog-generator@v4.3.1
      with:
        myToken: ${{ inputs.github-token }}
        head-ref: ${{ github.ref_name }}
        base-ref: ${{ env.PREV_TAG }}

    - name: "Publish to GitHub Repository"
      id: create_release
      uses: ncipollo/release-action@v1.14.0
      with:
        tag: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Grab the new version from Maven Central https://repo1.manven.org/maven2/net/kessra/test-release-pipeline/${{ github.ref_name }}/ by using it in your deps
          
          ```
          <dependencies>
            <dependency>
                <groupId>net.kessra</groupId>
                <artifactId>test-release-pipeline</artifactId>
                <version>${{ github.ref_name }}</version>
            </dependency>
          </dependencies>
          ```
          
          ### Things that changed in this release
          ${{ steps.changelog.outputs.changelog }}
        token: ${{ inputs.github-token }}